apiVersion: v1 
kind: Pod 
metadata:
  name: multi-container-pod-volume

spec:
  containers:
  - args: # first container
    - /bin/sh
    - -c 
    - sleep 3600
    name: container-1
    image: busybox
    resources: 
      limits:
        memory: 20Mi
        cpu: "0.5"
      requests:
        memory: 15Mi
    volumeMounts:
      - mountPath: '/etc/foo'
        name: log-volume
  - args: # Second container
    - /bin/bash
    - -c 
    - sleep 3600
    name: container-1
    image: busybox
    volumeMounts:
      - mountPath: '/etc/foo'
        name: log-volume
    resources: 
      limits:
        memory: 20Mi
        cpu: "0.5"
      requests:
        memory: 15Mi
    restartPolicy: Never
  volumes:
    - name: log-volume
      emptyDir:
        {}
      
     