# create the namespace ckad-prep
# kubectl set image pod mypod mypod=nginx
# kubectl run busybox --image=busybox --rm -it --restart=Never -- /bin/sh

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - name: mypod
      image: nginx:1.15.12
      resources:
        limits:
          cpu: 500Mi
          memory: 500Mi
        requests:
          cp: 500Mi
          memory: 1Gi
  restartPolicy: Never