apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-back
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80
      resources: {}
  restartPolicy: Never # or Always