apiVersion: batch/v1
kind: Job
metadata:
  name: first-jon
spec:
  template:
    spec:
      containers:
      - name: first-job
        image: alpine
        command: ["sh", "-c", "echo bonjour khazim"]
    restartPolicy: Never
  backoffLimit: 25
  parallelism: 3
  completions: 6