apiVersion: v1
kind: Service
metadata:
  name: MYAPP
  namespace: default
spec:
  clusterIP: None
  selector:
    app: MYAPP
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
# /etc/kubernetes/pki/users/dev-user/developer-user.crt