apiVersion: v1
kind: Pod
metadata:
  name: check-healthy
  labels:
    app: healthy-pod
spec:
  containers:
  - image: k8s.gcr.io/busybox
    name: liveness-pod
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    -  'while true; do echo $(date); sleep 1; done'
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
