apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - image: ningx
      name: nginx-pod
      resources: {} 
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec: 
  containers:
    - image: busybox
      name: busybox-pod
      command:
        - env
      stdin: true
      tty: true
  restartPolicy: Never
  # run command kubectl logs busybox-pod to show logs