apiVersion: apps/v1
kind: Deployment
metadata:
  name:  SERVICE-FRONTEND
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name:  road-service
        image:  khazim/frontend-service
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        ports:
        - containerPort:  8080
          name: frontend
        volumeMounts:
        - name: log-volume
          mountPath: /etc/app
      volumes:
        - name: log-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always