apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  selector:
    app: frontend
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: service-back
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000