apiVersion: v1
kind: Service
metadata:
  name: service-back
  namespace: default
spec:
  selector:
    app: backend
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: service-back
    protocol: TCP
    port: 80
    targetPort: 80