apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    app: mlt-container 
spec:
  containers:
    - name: app 
      image: busybox
      
      command:
      - /bin/sh
      - -c 
      - 'while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep 5; done;'
      volumeMounts:
        - name: log-volume
          mountPath: /var/logs
      resources: 
        limits:
          cpu: "1"
          memory: 100Mi
        requests:
          cpu: "2"
          memory: 100Mi
    - name: transformer
      image: busybox
      command:
      - "/bin/sh"
      - "-c"
      - 'sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;'
      volumeMounts:
        - name: log-volume
          mountPath: /var/logs
      resources: 
        limits:
          cpu: "1"
          memory: 100Mi
        requests:
          cpu: "2"
          memory: 100Mi
  volumes:
    - name: log-volume
      emptyDir: {}