apiVersion:  v1
kind: Pod
metadata:
  name: yellow
  labels:
    app: yellow
spec:
  containers:
  - name: gold
    image: redis
    imagePullPolicy: Always
    resources: 
      limits:
        cpu: 200m
        memory: 300Mi
  - command:
      - sleep
      - "1000"
    image: busybox
    name: lemon
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
